### ISSUE TITLE
Flatpak/Snap/AppImage releases?

### ISSUE THREAD

**Issue by macmpi** [mike632t/x11-calc#10]
Hi,
Thanks for providing those accurate beloved HP calculator simulators!
Would you consider providing easy to install packages in one/several of those popular formats?
Thanks.

**Comment by mike632t** [comment]
Yes - but I haven't a clue how to do so at the moment!

It isn't that hard to compile the simulators as there are very few dependencies, so you might want to down load the source code and try to compile it yourself in the meantime as it could be a while before I figure out how to build an appimage...

**Comment by macmpi** [comment]
FWIW there is a [nonpareil snap](https://snapcraft.io/nonpareil-cm) which could serve as an [example](https://github.com/cmatsuoka/nonpareil-snap/blob/master/snap/snapcraft.yaml) (albeit without voyager series).

**Comment by macmpi** [comment]
Took a first stab at preliminary Flatpak package: check [here](https://github.com/macmpi/x11-calc-flatpak)

**Comment by mike632t** [comment]
Feel free to continue to experiment with flatpak, but producing a portable binary wasn't one of my aims.  However, I'm going to leave this issue open for now to remind me, but if I do anything at all it will probably be to produce a DEBIAN package...

**Comment by macmpi** [comment]
Ok, got it.
How about leveraging  [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) in `x11-calc` to further facilitate portability (HOME/DATA and eventually CONF dirs)?

**Comment by macmpi** [comment]
done with https://flathub.org/apps/io.github.mike632t.x11-calc
