### ISSUE TITLE
Shortcut keys not working in FreeBSD

### ISSUE THREAD

**Issue by jonakeys** [mike632t/x11-calc#102]
I've built the voyager calculators, but can't use shortcut keys. The numbers nor the other shortcut keys work. When using the trackpad to click the buttons on the calculator, everything works great. But that is a bit cumbersome for practical usage.

**Comment by mike632t** [comment]
I've only tested the shortcut keys on Linux (and NetBSD).

If you want to see if you can get the shortkeys working you will need to modify `x11-keyboard.c` (line 51) `x11-keyboard.h` (line 28) and `x11-calc.c` (line 844) to include a test for the appropriate predefined macro for FreeBSD.. (`__FreeBSD__` ?)   

Note that It may not work unless all the keycode symbols needed are defined in `Xlib.h`.

I look forward to a second pull request if it works!



And yes I know `v_key_decode()` is a bit of a hack but it works!

**Comment by jonakeys** [comment]
Thanks for your directions. Defining FreeBSD make the shortcuts work as expected!
But I don't know how the A-E keys should work. On the readme you say "On programmable models 'A' - 'E' correspond to the function keys where they exist and 'Space' maps to 'SST' if not shifted." When I press f and than 'A' for example, it doesn't react. On the real device, the lbl A is executed.

**Comment by mike632t** [comment]
Well spotted - I must have written that a very long time ago before I added the voyager models!! (I does work on the HP67).

I'll push a change to the `testing` branch later (it isn't hard if you know what you forgot to do)

**Comment by mike632t** [comment]
On closer inspection I'm not sure if I should use A-E as shortcut keys on the 11C and 15C as the label isn;t the primary function but one the other hand I don't have shrt cuts for sqrt, eX etc...

**Comment by mike632t** [comment]
Just pushed version 0.14.0152 to `testing` - see what you think.  You do need to use UPPERCASE to avoid conflicting with other shortcut keys (eg 'e' which is already used for 'EEX') - keyboard should now work on FreeBSD without having to modify the code...

**Comment by jonakeys** [comment]
testing looks great to me, the shortcut keys can now also be used in FreeBSD! I added a PR #104 because there were two other lines that needed a supplement to make all compile.
Thanks for adding A-E also as keys, that makes the behaviour as also described in the readme. It's ofcourse your design choices and decisions, so if you rather would not like to include those keys in the emulators, that's fine with me also.

**Comment by mike632t** [comment]
If it makes sense to you than I'll leave it as is.  

The original implementation was to have a keyboard shortcut for just the primary key functions, so just A-B, A-E, and A-F on the HP34C, HP67 and HP16C.  Shortcuts for shifted functions make sense on the HP11C and HP15C but things will get more complicated with the HP41C as some keys will require multiple keyboard shortcuts... 

If everything is working do you want to close this issue?

**Comment by jonakeys** [comment]
Yes, it's good the way it is, I'll close this issue.
