### ISSUE TITLE
Fonts issue: clearer error msg & fallback

### ISSUE THREAD

**Issue by macmpi** [mike632t/x11-calc#16]
As you may have noticed flathub review process enlightened a potential font issue (Fedora in that case).

Maybe app error message could be improved to make it clearer for user which _specific fonts package_ to install.
Also how about in such case (while issuing error/warning) running app in "degraded" mode with a _very common_ (albeit uglier) font?
This would not block the app and motivate user to install proper fonts.

Thoughts?

**Comment by mike632t** [comment]
The '6x12' font has been a standard X11 bitmap font since at least 1993!  They don't come much uglier or common than that, however is on some newer systems the bitmap fonts are not always installed.

The problem is that unless you happen to be familiar with the package names used by the different distributions for all the different fonts (and I'm not) just finding which package contains the font (or fonts) you need can be a challenge.  Some distributions make it easier than others.  Debian allows you to search by [partial file name](https://packages.debian.org/search?suite=bookworm&arch=any&mode=filename&searchon=contents&keywords=6x12) for example.  Fedora is particularly awkward in this case as the package name containing the files has changed between releases.

The best I can think of is to expand the error message with a short explanation `Cannot load font '6x12' (x11 bitmap fonts required)` ...

**Comment by macmpi** [comment]
Maybe you can exemplify the naming on debian and Fedora?
Now, can this error be non-blocking and still display the calculator with another most basic font (which is likely to be anywhere) as a base, even if it does not look great?

(BTW you may update the readme with the current font name on Fedora, now we know `xorg-x11-fonts-misc.noarch`)

**Comment by macmpi** [comment]
A fall-back mechanism with very basic fonts would clear-us from bundling the fonts (and potentially complex side-cases with native installs) and would be probably enough to pass validation...

**Comment by mike632t** [comment]
From my perspective the clue it in the name - On UNIX fonts don't come any more basic than `xfonts-base` !  (Bitmap, not scale-able, not aliased etc)  

However if I can identify another suitable font the same size by name I can try that if loading `6x12` fails, and it turns out there is a precedent as looking in `x11-fonts.h` it would seem that for VMS I had to use different font names as the fonts it uses predate the current `.pcf` font files on UNIX by about a decade!  Finding font name used by X11 isn't as easy as it sounds though!

Note - We actually need 4 fonts to replace 
```
#define NORMAL_TEXT    "6x12" /* Font to use for function keys. */
#define SMALL_TEXT     "6x10" /* Font to use for shifted functions. */
#define LARGE_TEXT     "6x13" /* Font to use for numeric keys. */
#define ALTERNATE_TEXT "5x8" /* Font to use for alternate functions. */
```

Which version of Fedora were you using ?  I'm pretty sure the last version I tested was 35 I'll update the README.

**Comment by macmpi** [comment]
I built a Fedora39 VM this afternoon to test the issue. I can still use it for further tests.
I'm not much familiar about where fonts need to be, and if it's same location across different linux distros.
If there is some consistency, maybe I can indeed add them into flatpak and your app would find them where it expects to?
Doing some [reading](https://github.com/flatpak/flatpak/issues/4097).
That's clearly the #1 issue to solve to get published.

**Comment by mike632t** [comment]
It isn't consistent, and it isn't just a matter of putting some files somewhere, fonts need to be registered etc

See this answer on [stackoverflow](https://superuser.com/questions/465142/)

**Comment by mike632t** [comment]
If you can find a 12 point font on Fedora that loads in xterm I should be able to try using it...

**Comment by mike632t** [comment]
Think I've got it

```
#define NORMAL_TEXT    "*-fixed-*-*-*-*-10-*" /* Font to use for function keys. */
#define SMALL_TEXT     "*-fixed-*-*-*-*-10-*" /* Font to use for shifted functions. */
#define LARGE_TEXT     "*-fixed-*-*-*-*-12-*" /* Font to use for numeric keys. */
#define ALTERNATE_TEXT "*-fixed-*-*-*-*-8-*"  /* Font to use for alternate functions. */
```

Spot the difference!!

![Screenshot at 2024-02-22 21-18-56](https://github.com/mike632t/x11-calc/assets/1799044/4e33be15-e122-42c7-afd1-57406020063a)

**Comment by mike632t** [comment]
Pushed potential solution to `unstable`.  I suggest testing it with and without the base fonts package installed.

 I'd be very interested in the screenshots!

**Comment by macmpi** [comment]
tried a new build from unstable. Worked fine on my elementary machine, but fails on FedoraVM with previous font removed (works with `xorg-x11-fonts-misc` installed):
```
flatpak run io.github.mike632t.x11_calc 
x11-calc-34c : Cannot load font '*-fixed-*-*-*-*-10-*'.
```
[x11-calc.flatpak.tar.gz](https://github.com/mike632t/x11-calc/files/14380189/x11-calc.flatpak.tar.gz)

FWIW, I enclose font list from base Fedora install: [fc-list.txt](https://github.com/mike632t/x11-calc/files/14380278/fc-list.txt).
Installing `xterm` adds `xorg-x11-fonts-misc-7.5-36.fc39.noarch` as dependency: so is not there by default...

You may find [this](https://wiki.archlinux.org/title/Xterm#Fonts) interesting.
On Fedora: 
```
fc-match mono
NotoSansMono[wght].ttf: "Noto Sans Mono" "Regular"
```
on my elementaryOS:
```
fc-match mono
Cousine-Regular.ttf: "Cousine" "Regular"
```

**Comment by mike632t** [comment]
What do you get if you run `xlsfonts` ?

**Comment by macmpi** [comment]
[xlsfonts.txt](https://github.com/mike632t/x11-calc/files/14382881/xlsfonts.txt)

**Comment by macmpi** [comment]
I may try a trick on the flatpak side of things.
Which one(s) would you need among these: https://xorg.freedesktop.org/releases/individual/font/

EDIT:
seems like [font-alias-1.0.5.tar.xz](https://xorg.freedesktop.org/releases/individual/font/font-alias-1.0.5.tar.xz) says:
5x8          -misc-fixed-medium-r-normal--8-80-75-75-c-50-iso8859-1
6x10         -misc-fixed-medium-r-normal--10-100-75-75-c-60-iso8859-1
6x12         -misc-fixed-medium-r-semicondensed--12-110-75-75-c-60-iso8859-1
6x13         -misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso8859-1

**Comment by mike632t** [comment]
They should work (emphasis on should).

In theory if those fonts are available (__and registered__) then those font names will match one of the the wild card patterns (`'*-fixed-*-*-*-*-10-*'` , `*-fixed-*-*-*-*-12-*'` , and `'*-fixed-*-*-*-*-8-*'`) specified when the program tries to load a matching font.

I could also try using `lucidasans-10`, `lucidasans-12`, and `lucidasans-8` as an alternative but I can't test that easily I don't have those fonts on my system!  (I'll be able to finish building a Fedora 39 VM when I get home from work)

**Comment by mike632t** [comment]
I did see something about the font search paths that Flatpak can use which I think is the trick you are referring to...

**Comment by macmpi** [comment]
> I did see something about the font search paths that Flatpak can use which I think is the trick you are referring to...

Yes: I'm looking into installing those [fonts](https://github.com/mike632t/x11-calc/issues/16#issuecomment-1960955702) from sources (from launcher script). Not sure will succeed though as it needs a bunch of deps...
EDIT: giving-up. EDIT2: nope, I think I'm getting to it :wink:

If you manage to use `lucidasans-10`, `lucidasans-12`, and` lucidasans-8` , that would be much-much easier for Fedora fallback!

It seems only common from my Ubuntu/eOS and Fedora are:
```
-misc-fixed-medium-r-semicondensed--0-0-75-75-c-0-iso8859-1
-misc-fixed-medium-r-semicondensed--13-100-100-100-c-60-iso8859-1
-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso8859-1
6x13
cursor
fixed
```

**Comment by mike632t** [comment]
Pushed a version using `lucidasans-10`, `lucidasans-12`, and `lucidasans-8` to `unstable` just for testing

**Comment by macmpi** [comment]
getting closer:
```
fc-list | grep data
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/6x13.bdf: Fixed:style=SemiCondensed
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/6x13B.bdf: Fixed:style=Bold SemiCondensed
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/7x13.bdf: Fixed:style=Regular
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/8x13.bdf: Fixed:style=Regular
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/7x14.bdf: Fixed:style=Regular
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/9x18B.bdf: Fixed:style=Bold
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/8x13B.bdf: Fixed:style=Bold
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/9x15B.bdf: Fixed:style=Bold
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/5x8.bdf: Fixed:style=Regular
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/10x20.bdf: Fixed:style=Regular
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/4x6.bdf: Fixed:style=Regular
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/6x9.bdf: Fixed:style=Regular
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/5x7.bdf: Fixed:style=Regular
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/6x10.bdf: Fixed:style=Regular
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/18x18ja.bdf: Fixed:style=ja
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/7x13O.bdf: Fixed:style=Oblique
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/8x13O.bdf: Fixed:style=Oblique
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/6x13O.bdf: Fixed:style=Oblique SemiCondensed
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/18x18ko.bdf: Fixed:style=ko
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/9x18.bdf: Fixed:style=Regular
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/9x15.bdf: Fixed:style=Regular
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/7x14B.bdf: Fixed:style=Bold
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/7x13B.bdf: Fixed:style=Bold
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/6x12.bdf: Fixed:style=SemiCondensed
/home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/12x13ja.bdf: Fixed:style=ja
```
EDIT: coming from https://xorg.freedesktop.org/releases/individual/font/font-misc-misc-1.1.3.tar.gz

**Comment by mike632t** [comment]
> ```
> -misc-fixed-medium-r-semicondensed--0-0-75-75-c-0-iso8859-1
> -misc-fixed-medium-r-semicondensed--13-100-100-100-c-60-iso8859-1
> -misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso8859-1
> 6x13
> cursor
> fixed
> ```

That is a bit of a pain - Apart from the cursor font they basically all amount to the same thing (a fixed width 13 point font), and that just doesn't work!

**Comment by mike632t** [comment]
>```
> /home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/6x13.bdf: Fixed:style=SemiCondensed
>
> /home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/5x8.bdf: Fixed:style=Regular
>
> /home/vboxuser/.var/app/io.github.mike632t.x11_calc/data/fonts/bitmap/6x12.bdf: Fixed:style=SemiCondensed
> ```

Those three will proabably do me !  (They might even have the same names).

**Comment by mike632t** [comment]
Before you package again - I do have a bug fix I need to push to stable..

**Comment by macmpi** [comment]
> Those three will proabably do me ! (They might even have the same names).

Did not see you lucida patch on unstable.
I'm still having this on unstable
```
flatpak run io.github.mike632t.x11_calc
x11-calc-25c : Cannot load font '*-fixed-*-*-*-*-10-*'.
```
Stable is not happy either.
```
flatpak run io.github.mike632t.x11_calc 
x11-calc-25c : Cannot load font '6x12'.
```
Unsure .bdf format is causing an issue: can you use those?

Not ready for new package yet :smile:

EDIT: `xlsfonts` does not list them though (only `fc-list` does)...
Can't do [xset](https://hea-www.harvard.edu/~fine/Tech/font-howto.html) magics as utility is not available in Fedora base...

**Comment by mike632t** [comment]
Unfortunately for 'X11 core fonts' you have to use `xset`.

Just for testing I've created a `flatpak` branch:
```
#define NORMAL_TEXT    "lucidasans-10" /* Font to use for function keys. */
#define SMALL_TEXT     "lucidasans-10" /* Font to use for shifted functions. */
#define LARGE_TEXT     "lucidasans-12" /* Font to use for numeric keys. */
#define ALTERNATE_TEXT "lucidasans-8"  /* Font to use for alternate functions. */
```

**Comment by mike632t** [comment]
I've found the source code for [xset](https://github.com/ystk/debian-x11-xserver-utils/tree/master/xset) and compiling it is a one liner, provided `libxmu-dev` is available...

```
cc xset.c -o xset -lX11 -lXmu
```

**Comment by mike632t** [comment]
I think I've made some progress... 

![Screenshot_fedora39_2024-02-23_23:54:24](https://github.com/mike632t/x11-calc/assets/1799044/96357fc0-bb9f-4e04-a698-0ba66db469ff)

It isn't perfect as the available fonts don't include all the characters so there are some square boxes if you look closely, but it does not complain!

**Comment by macmpi** [comment]
I'm struggling building `xset`: in the sandbox, libraries are in:
```
/run/host/lib64/libXmu.so.6
/run/host/lib64/libXmuu.so.1
/run/host/lib64/libXmu.so.6.2.0 
/run/host/lib64/libXmuu.so.1.0.0
```

**Comment by macmpi** [comment]
> I think I've made some progress...

Congrats: it DOES look great!
I just tested on my end: works on both Ubuntu & Fedora (% is even more readable on the latter!)
I'm giving-up `xset` stuff: leaving aside the compile issues, it does not even work if I use host-side version.

Hopefully Gentoo has proper base fonts...
Let me know when you make new stable with assorted tag: I'll update flatpak files.

**Comment by mike632t** [comment]
OK I've updated the code so that for each type of font needed I can specify a 'list' of alternative fonts, and I've included in the list both the X11 base font and the alternative fonts we tested yesterday.  Rather neatly it also allowed me to get rid of the VMS specific font definitions as well as all I had to do was add them to each list.

I did think about allowing the fonts to be defined in a configuration file (along with other attributes like the window position etc) but that is more complicated than it needs to be for now!

Can you test the new code which I've pushed to the `unstable` branch (I probably should have created a separate branch for this fix but I forgot).

**Comment by macmpi** [comment]
> Can you test the new code which I've pushed to the `unstable` branch

```
make[1]: *** No rule to make target 'x11-calc-font.c', needed by 'x11-calc.o'.  Stop.
make: *** [makefile:63: hp35] Error 2
```

**Comment by mike632t** [comment]
Found the problem - x11-calc-fonts.c is missing...

**Comment by macmpi** [comment]
rebuilt flatpak, and it seems to work fine on elementaryOS and Fedora :rocket:

**Comment by mike632t** [comment]
Trying to decide if `-*-courier-medium-r-*-*-11-*` looks better than `-*-helvetica-medium-r-*-*-11-*`  ...

![Screenshot at 2024-02-24 22-48-32](https://github.com/mike632t/x11-calc/assets/1799044/d0c8d1f9-824f-45c8-9c17-3881c5dc5e04)

I'm using `xfontsel -print` to display the available fonts which allow me to see what options are available.

**Comment by macmpi** [comment]
> Trying to decide if `-*-courier-medium-r-*-*-11-*` looks better than `-*-helvetica-medium-r-*-*-11-*` ...

If it matters, I tend to prefer left side: closer to original with matching fonts. Right is a bit big (though some may find more readable)...

**Comment by mike632t** [comment]
I preferred the helvetica font style but it is just too big (for some reason the 8 point helvetica font isn't available), and only the smaller font works for anything with two rows of text above the keys (Voyager and Spice series).

**Comment by macmpi** [comment]
Saw you pushed to stable: fine.
Any other thing pending before you tag it?
Tagging it will probably trigger a PR on the flathub repo.

**Comment by mike632t** [comment]
Would like to test it still compiles on Tru64 UNIX - have some other stuff to do as well but should be able to tag the release in a few hours time.

**Comment by mike632t** [comment]
Just updated the version number and created a new release...

**Comment by mike632t** [comment]
New launcher provides guidance to a user if fonts are not available and the emulator will attempt to use an alternative font if available (though it may not look as good)
