### ISSUE TITLE
ON/OFF switch exit: does not work on voyager model

### ISSUE THREAD

**Issue by macmpi** [mike632t/x11-calc#17]
Tried [this](https://github.com/mike632t/x11-calc#exiting) on various models: it mostly works, but does not on some/all voyager model(s) (i.e 11c).

**Comment by mike632t** [comment]
It won't work on any of the Voyager series, they use buttons so they don't have (sliding) switches. (I ought to make that bit clearer).

The Voyager series also don't turn off when you think they do either... 


For some fun you can see what happens by using the breakpoint option (-b).
```
x11-calc-10c -r x11-calc-10c.rom -b 10
```
Press the off button and you should see the following.
```
** break **
0-008  04e   c = 0 all	
```
You can now release the button and use `ctrl-s` to single step through the firmware, it will get to a power off instruction after executing some 54 instructions...

**Comment by mike632t** [comment]
Updated README
