### ISSUE TITLE
Missing font on Arch Linux

### ISSUE THREAD

**Issue by Overscore** [mike632t/x11-calc#2]
Hello, I get the following error message on an Arch Linux:

**_make clean_**
**_make all_**
x11-calc-25
**_./x11-calc-25_** 
x11-rpncalc: Version 0.2 [Commit ID: $Format:%h$] 10 Oct 21 10:35:07 (Build: 0058)
x11-rpncalc : Cannot load font '6x12'.

What can I do?
TIA

**Comment by mike632t** [comment]
> > The result suggests you need `xorg-fonts-misc` but I'm not an Arch user so I can't test it.
> 
> I did that. Installing `xorg-fonts-misc` pulls also in `xorg-fonts-alias-misc`. The result is the same as above: x11-rpncalc : Cannot load font '6x12'

That is very odd `usr/share/fonts/misc/6x12.pcf.gz` is in the list of files in that package.  Something else is missing...   Does `fonts.dir` exist on your system and is it updated when you install `xorg-fonts-misc` ?

If it is possible to post a list of the packages you have installed I might have a go at reproducing the problem, it seems like the sort of minimal environment I like.

**Comment by mike632t** [comment]
Can you provide a list of all your installed packages?

**Comment by mike632t** [comment]
Now that I know a bit more about how fonts work I've implemented a falback mechanism which will switch to the an adobe courier font if the x11 base fonts are not available (#16 ).

Note that if the fallback font isn't available you will still get the original error message (as that is the desired font)

**Comment by dxcSithLord** [comment]
Cool, thanks for the heads up!
