### ISSUE TITLE
enabling xWayland support

### ISSUE THREAD

**Issue by macmpi** [mike632t/x11-calc#35]
Looked a bit more at this, and capturing some observation here.
[overview](https://wayland.freedesktop.org/docs/html/ch05.html)

Starting app on wayland (i.e. Fedora) gives the following error:
`x11-calc-11c: Cannot connect to X server ''.
`
[Using](https://github.com/mike632t/x11-calc/blob/25f88c9af640864ddcbe83bb5bb60efe8d008f9d/src/x11-calc.c#L602) default  [display name](https://github.com/mike632t/x11-calc/blob/25f88c9af640864ddcbe83bb5bb60efe8d008f9d/src/x11-calc.c#L386)  is **probably a root cause**.

Indeed looking at environment variables display name is different:
Baseline x11 system - working:
```
[📦 io.github.mike632t.x11-calc ~]$ echo $XDG_SESSION_TYPE
x11
[📦 io.github.mike632t.x11-calc ~]$ echo $WAYLAND_DISPLAY

[📦 io.github.mike632t.x11-calc ~]$ echo $DISPLAY
:99.0
```
Wayland environment (Fedora) - failing:
```
[📦 io.github.mike632t.x11-calc ~]$ echo $XDG_SESSION_TYPE
wayland
[📦 io.github.mike632t.x11-calc ~]$ echo $WAYLAND_DISPLAY
wayland-0
[📦 io.github.mike632t.x11-calc ~]$ echo $DISPLAY
```
Discussed [here](https://github.com/keybase/client/issues/19614)

**Comment by mike632t** [comment]
On Linux the default display is is defined by the `DISPLAY` environment variable.  To see this in action you can start a second xserver (which will run in a window on your existing desktop) using the following command (assuming ":1" is not already in use).  You may need to install `xserver-xephyr`, and I'm not sure if it is supported on Wayland as it uses X11! 
```
 Xephyr :1 -listen inet -br -ac -from localhost -screen 1024x768
```
Then if you launch the emulator using 
```
bin/x11-calc-33c
```
It will use your default desktop (which is probably ":0") as normal.

However, if you launch it using:
```
DISPLAY=:1 bin/x11-calc-33c
```
The display will use the other xserver.  Note that the application window will be drawn without any borders as there is no window manager available to draw them..

So if  `DISPLAY=:99.0` is defined I'd expect this to be used as the default display, and if you get the message `Cannot connect to X server ''.` then it probably means what it says...   (Usually that the sever not running or the connection was blocked).

**Comment by macmpi** [comment]
in the example I gave with `DISPLAY=:99.0`, your current implementation just works as expected (no error).

Problem comes in wayland cases (undefined `DISPLAY`, but `WAYLAND_DISPLAY=wayland-0`): in that case X server is not found. Maybe using `wayland-0` instead would fix it?...

**Comment by macmpi** [comment]
On wayland hosts, flatpak enables `Xwayland` access in sandbox only with `--socket=x11` option.
With `--socket=wayland --socket=fallback-x11` Xwayland is filtered-out, hence only native wayland would work on wayland host (fallback x11 is activated on non-wayland host).

So in our case, there is no alternative to `--socket=x11` option.
