### ISSUE TITLE
Backspace key to clx

### ISSUE THREAD

**Issue by Zorgodon** [mike632t/x11-calc#4]
Could you map the backspace key to clx as it's easier to reach than escape?
I took a peek at the code but couldn't find where the X11 keysyms actually get processed.

**Comment by mike632t** [comment]
No problem done in commit '80a9236'.

Each button can only have one shortcut key assigned to it, so to allow both Escape and BackSpace to be used for 'CLX' I simply check for a BackSpace and remap it ti Escape.

**Comment by Zorgodon** [comment]
Thanks. So the mappings are in the 2nd column of h_button in each respective calculator's .c file. However, 'Enter' is keycode 36 in xev but 15 in the mapping, so I'm not sure how to convert the keycodes.

**Comment by mike632t** [comment]
> So the mappings are in the 2nd column of h_button in each respective calculator's .c file

Yes 

As regards the key strokes the magic happens in 'x11-keyboard.c' where I use 'v_key_decode()' to decode the X11 key codes into 7-bit ASCII.  (I got fed up with trying to keep track of the state of the shift and control keys in the main program). 

This makes a 'Enter'  on the numeric key pad and 'Return' on the keyboard both return 015 (octal) which it what the ENTER key is bound to.

Currently this only works for Linux systems, I need to get around to working out how to make this work on VMS and Tru64 UNIX one day!
